[package]
name = "xc2par"
version = "0.0.1"

[profile.release]
lto = true

[lib]
name = "xc2par"
crate-type = ["rlib", "staticlib"]

[dependencies]
openfpga-xbpar-rs = { path = "../xbpar-rs" }
xc2bit = { path = "../xc2bit" }
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
